### ISSUE TITLE
add delimiter inside li

### ISSUE THREAD

**Issue by yeshansachithak** [nobuti/Codeigniter-breadcrumbs#10]
How to add delimiter inside of the li. For now when I `<?php echo set_breadcrumb(); ?>` it will return `<ul><li><a href="home_link_href">Home</a></li> > <li>Item</li>` but I need to use this delimiter inside in li as below
`<ul><li><a href="">Home</a> > </li><li>Item</li></ul>`

please give me a update

**Comment by nobuti** [comment]
It's an edge case, right now the delimiter position is not configurable. You could set `$config['crumb_divider'] = '';` and handle it at css level, something like this:
```
a:after {
   content: '>';
   display: inline-block;
}
